### ISSUE TITLE
Feat: Info 페이지 구현

### ISSUE THREAD

**Issue by seungsimdang** [12-Cookie/cookie-s#16]
## Description

Info 페이지 구현

## Todo

- [x] Staff Info 페이지 구현
- [x] Admin Info 페이지 구현 
- [x] CompanyCode 페이지 구현
